(() => {
  const app=document.getElementById("app"),data=window.GAME_DATA,scenes=Object.fromEntries(data.scenes.map(s=>[s.id,s]));
  const S1="popup_scene",S2="popup_team";
  const norm=v=>String(v??"").trim().replace(/\s+/g,"").toLowerCase();
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
  const params=new URLSearchParams(location.search),qr=params.get("qr"),qrScene=qr?data.qr[String(qr).toUpperCase()]:null;
  let state={sceneId:qrScene||localStorage.getItem(S1)||"start",team:localStorage.getItem(S2)||""};
  const save=()=>{localStorage.setItem(S1,state.sceneId);localStorage.setItem(S2,state.team)};
  const go=id=>{state.sceneId=id;save();history.replaceState({},"",location.pathname);render();scrollTo({top:0,behavior:"smooth"})};
  const fill=t=>String(t??"").replaceAll("{{team}}",state.team||"OO");
  const top=()=>{const i=data.scenes.findIndex(s=>s.id===state.sceneId),p=Math.max(0,Math.round(i/(data.scenes.length-1)*100));return `<div class="topbar"><div class="logo">🍿 POP UP</div><div class="progress">進度 ${p}%</div></div>`};
  const shell=(s,b)=>`${top()}<section class="card">${s.kicker?`<div class="kicker">${esc(s.kicker)}</div>`:""}${s.title?`<h1 class="scene-title">${esc(s.title)}</h1>`:""}${b}<hr><button class="btn ghost" id="resetBtn">清除進度並重來</button></section>`;
  const bindReset=()=>document.getElementById("resetBtn")?.addEventListener("click",()=>{if(confirm("確定要清除目前進度嗎？")){localStorage.removeItem(S1);localStorage.removeItem(S2);state={sceneId:"start",team:""};render()}});
  function render(){const s=scenes[state.sceneId]||scenes.start;
    if(s.type==="hero"){app.innerHTML=`${top()}<section class="card hero"><div class="badge">Alpha 0.2</div><h1>${esc(s.title)}</h1><p>${esc(s.text)}</p><div class="controls"><button class="btn" id="startBtn">開始遊戲</button>${localStorage.getItem(S1)&&localStorage.getItem(S1)!=="start"?`<button class="btn secondary" id="continueBtn">繼續上次進度</button>`:""}</div></section>`;document.getElementById("startBtn").onclick=()=>go("contact");document.getElementById("continueBtn")?.addEventListener("click",()=>go(localStorage.getItem(S1)));return}
    if(s.type==="dialogue"){app.innerHTML=shell(s,`<div class="stage">〔${esc(s.scene||"場景")}臨時背景〕</div><div class="speaker">${esc(s.speaker)}</div><div class="dialogue">${esc(fill(s.text))}</div><div class="controls"><button class="btn" id="nextBtn">繼續</button></div>`);document.getElementById("nextBtn").onclick=()=>go(s.next);bindReset();return}
    if(s.type==="answer"){app.innerHTML=shell(s,`<div class="stage">〔${esc(s.kicker||"互動場景")}臨時背景〕</div><label class="note" for="answer">${esc(s.prompt)}</label><input class="input" id="answer" autocomplete="off"><div class="feedback" id="feedback"></div><div class="controls"><button class="btn" id="submitBtn">送出答案</button></div>`);const submit=()=>{const ok=s.answers.some(a=>norm(a)===norm(document.getElementById("answer").value)),f=document.getElementById("feedback");if(ok){f.className="feedback ok";f.textContent=s.success||"答案正確。";setTimeout(()=>go(s.next),350)}else{f.className="feedback";f.textContent="答案不正確，請再檢查線索。"}};document.getElementById("submitBtn").onclick=submit;document.getElementById("answer").onkeydown=e=>{if(e.key==="Enter")submit()};bindReset();return}
    if(s.type==="team"){app.innerHTML=shell(s,`<label class="note" for="team">${esc(s.prompt)}</label><input class="input" id="team" maxlength="24" value="${esc(state.team)}"><div class="feedback" id="feedback"></div><div class="controls"><button class="btn" id="submitBtn">建立團隊</button></div>`);document.getElementById("submitBtn").onclick=()=>{const v=document.getElementById("team").value.trim();if(!v){document.getElementById("feedback").textContent="請輸入團隊名稱。";return}state.team=v;save();go(s.next)};bindReset();return}
    if(s.type==="confirm"){app.innerHTML=shell(s,`<div class="stage">〔${esc(s.scene||"實體互動")}臨時背景〕</div><div class="dialogue">${esc(s.text)}</div><div class="controls"><button class="btn" id="nextBtn">${esc(s.button||"完成")}</button></div>`);document.getElementById("nextBtn").onclick=()=>go(s.next);bindReset();return}
    if(s.type==="multi"){app.innerHTML=shell(s,`<p class="note">請將每位角色遺失的物品填入對應欄位。</p><div class="item-grid">${s.fields.map(([n])=>`<div class="item-row"><label for="field_${esc(n)}">${esc(n)}</label><input class="input" id="field_${esc(n)}"></div>`).join("")}</div><div class="feedback" id="feedback"></div><div class="controls"><button class="btn" id="submitBtn">確認全部答案</button></div>`);document.getElementById("submitBtn").onclick=()=>{const wrong=s.fields.filter(([n,a])=>norm(document.getElementById(`field_${n}`).value)!==norm(a)),f=document.getElementById("feedback");if(!wrong.length){f.className="feedback ok";f.textContent="全部正確。";setTimeout(()=>go(s.next),350)}else{f.className="feedback";f.textContent=`還有 ${wrong.length} 個欄位不正確。`}};bindReset();return}
    if(s.type==="ending"){app.innerHTML=shell(s,`<div class="stage">〔白光擴散，準備進入電影世界〕</div><div class="dialogue">${esc(s.text)}</div><div class="badges"><span class="badge">✓ 協尋網站</span><span class="badge">✓ 光之電影院</span><span class="badge">✓ 第18影廳</span></div>`);bindReset()}
  }
  render();
})();
