(() => {
const app=document.getElementById("app"),data=window.GAME_DATA,scenes=Object.fromEntries(data.scenes.map(s=>[s.id,s]));
const S1="popup_scene",S2="popup_team";const norm=v=>String(v??"").trim().replace(/\s+/g,"").toLowerCase();const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
let state={sceneId:localStorage.getItem(S1)||"start",team:localStorage.getItem(S2)||""};
const save=()=>{localStorage.setItem(S1,state.sceneId);localStorage.setItem(S2,state.team)};const go=id=>{state.sceneId=id;save();render();scrollTo({top:0,behavior:"smooth"})};const fill=t=>String(t??"").replaceAll("{{team}}",state.team||"OO");
const top=()=>`<div class="topbar"><div class="logo">🍿 POP UP</div><div class="progress">進度 ${Math.max(0,Math.round(data.scenes.findIndex(s=>s.id===state.sceneId)/(data.scenes.length-1)*100))}%</div></div>`;
const shell=(s,b)=>`${top()}<section class="card">${s.kicker?`<div class="kicker">${esc(s.kicker)}</div>`:""}${s.title?`<h1 class="scene-title">${esc(s.title)}</h1>`:""}${b}<hr><button class="btn ghost" id="resetBtn">清除進度並重來</button></section>`;
function reset(){localStorage.clear();state={sceneId:"start",team:""};render()}
function missingMarkup(){return `<section class="missing-site"><header class="site-head"><div class="site-logo">FINDING</div><div class="site-small">失蹤人口協尋平台</div></header><div class="float-photo"></div><div class="float-photo"></div><div class="float-photo"></div><div class="float-photo"></div><div class="poster-wrap"><article class="poster"><div class="poster-title">尋人啟事</div><div class="poster-sub">帕普一家失蹤</div><div class="missing-main-photo"></div><div class="poster-copy">帕普一家於昨日進入光之電影院後失去聯絡。若您願意協助尋找，請按下方按鈕與家屬聯繫。</div><button class="help-btn" id="helpBtn">我要協尋</button></article></div></section>`}
function render(){
const s=scenes[state.sceneId]||scenes.start;
if(s.type==="missing_home"){app.innerHTML=missingMarkup();document.getElementById("helpBtn").onclick=()=>{app.insertAdjacentHTML("beforeend",`<div class="overlay" id="overlay"><div class="modal"><h2>請輸入聯絡號碼</h2><input class="phone-input" id="phone" inputmode="numeric" autocomplete="off"><div class="feedback" id="phoneFeedback"></div><button class="modal-btn" id="callBtn">撥打電話</button></div></div>`);document.getElementById("callBtn").onclick=()=>{const v=document.getElementById("phone").value;if(norm(v)!=="90970915"){document.getElementById("phoneFeedback").textContent="聯絡號碼不正確。";return}document.getElementById("overlay").innerHTML=`<div class="modal"><div class="calling-icon">☎</div><div class="calling-name">正在為您接通帕普・寇恩</div><div class="dots"><i></i><i></i><i></i></div></div>`;setTimeout(()=>go("corn_1"),2200)}};return}
if(s.type==="phone_dialogue"){const isPlayer=s.speaker==="你們";app.innerHTML=`<section class="phone-scene"><div class="phone-status">與帕普・寇恩通話中</div><div class="dialogue-sheet"><div class="dialogue-inner"><div class="speaker-tag ${isPlayer?"player":"corn"}">${esc(s.speaker)}</div><div class="dialogue-text">${esc(fill(s.text))}</div>${s.teamInput?`<div class="team-box"><input id="teamInput" maxlength="24" placeholder="請輸入你們的團隊名稱"><button class="reply-btn" id="replyBtn">確認團隊名稱</button></div>`:`<button class="reply-btn" id="replyBtn">${esc(s.reply||"繼續")}</button>`}</div></div></section>`;document.getElementById("replyBtn").onclick=()=>{if(s.teamInput){const v=document.getElementById("teamInput").value.trim();if(!v)return;state.team=v;save()}go(s.next)};return}
if(s.type==="dialogue"){app.innerHTML=shell(s,`<div class="stage">〔${esc(s.scene||"場景")}臨時背景〕</div><div class="speaker">${esc(s.speaker)}</div><div class="dialogue">${esc(fill(s.text))}</div><div class="controls"><button class="btn" id="nextBtn">繼續</button></div>`);document.getElementById("nextBtn").onclick=()=>go(s.next)}
else if(s.type==="answer"){app.innerHTML=shell(s,`<div class="stage">〔${esc(s.kicker||"互動場景")}臨時背景〕</div><label class="note">${esc(s.prompt)}</label><input class="input" id="answer"><div class="feedback" id="feedback"></div><div class="controls"><button class="btn" id="submitBtn">送出答案</button></div>`);const sub=()=>{const ok=s.answers.some(a=>norm(a)===norm(document.getElementById("answer").value));document.getElementById("feedback").textContent=ok?(s.success||"答案正確。"):"答案不正確，請再檢查線索。";if(ok)setTimeout(()=>go(s.next),350)};document.getElementById("submitBtn").onclick=sub}
else if(s.type==="confirm"){app.innerHTML=shell(s,`<div class="stage">〔${esc(s.scene||"實體互動")}臨時背景〕</div><div class="dialogue">${esc(s.text)}</div><div class="controls"><button class="btn" id="nextBtn">${esc(s.button||"完成")}</button></div>`);document.getElementById("nextBtn").onclick=()=>go(s.next)}
else if(s.type==="multi"){app.innerHTML=shell(s,`<div class="item-grid">${s.fields.map(([n])=>`<div class="item-row"><label>${esc(n)}</label><input class="input" id="f_${esc(n)}"></div>`).join("")}</div><div class="feedback" id="feedback"></div><div class="controls"><button class="btn" id="submitBtn">確認全部答案</button></div>`);document.getElementById("submitBtn").onclick=()=>{const wrong=s.fields.filter(([n,a])=>norm(document.getElementById(`f_${n}`).value)!==norm(a));document.getElementById("feedback").textContent=wrong.length?`還有 ${wrong.length} 個欄位不正確。`:"全部正確。";if(!wrong.length)setTimeout(()=>go(s.next),350)}}
else if(s.type==="ending"){app.innerHTML=shell(s,`<div class="stage">〔白光擴散〕</div><div class="dialogue">${esc(s.text)}</div>`)}
document.getElementById("resetBtn")?.addEventListener("click",()=>{if(confirm("確定清除進度？"))reset()})
}
render();
})();